"""lessons: add bot_user_id

Revision ID: 40be355a50c8
Revises: 4793eb775ec2
Create Date: 2026-05-15 10:52:24.192158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40be355a50c8'
down_revision: Union[str, Sequence[str], None] = '4793eb775ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lesson_bot_chats_bot_user_id_fkey'), 'lesson_bot_chats', type_='foreignkey')
    op.drop_column('lesson_bot_chats', 'bot_user_id')
    op.add_column('lessons', sa.Column('bot_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_lessons_bot_user_id'), 'lessons', ['bot_user_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'users', ['bot_user_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_bot_user_id'), table_name='lessons')
    op.drop_column('lessons', 'bot_user_id')
    op.add_column('lesson_bot_chats', sa.Column('bot_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('lesson_bot_chats_bot_user_id_fkey'), 'lesson_bot_chats', 'users', ['bot_user_id'], ['user_id'])
    # ### end Alembic commands ###
