"""comment bot

Revision ID: 463c0b1a5087
Revises: c4ff95307cf7
Create Date: 2026-04-29 14:42:37.207026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463c0b1a5087'
down_revision: Union[str, Sequence[str], None] = 'c4ff95307cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bot_sessions_chat_id_key'), 'bot_sessions', type_='unique')
    op.drop_constraint(op.f('bot_sessions_chat_id_fkey'), 'bot_sessions', type_='foreignkey')
    op.drop_column('bot_sessions', 'chat_id')
    op.create_foreign_key(None, 'chat_user_states', 'messages', ['cleared_until_message_id'], ['message_id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'chat_user_states', 'messages', ['last_read_message_id'], ['message_id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_user_states', type_='foreignkey')
    op.drop_constraint(None, 'chat_user_states', type_='foreignkey')
    op.add_column('bot_sessions', sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('bot_sessions_chat_id_fkey'), 'bot_sessions', 'chats', ['chat_id'], ['chat_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('bot_sessions_chat_id_key'), 'bot_sessions', ['chat_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
