"""lessons

Revision ID: 4793eb775ec2
Revises: 463c0b1a5087
Create Date: 2026-05-13 15:55:56.217890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4793eb775ec2'
down_revision: Union[str, Sequence[str], None] = '463c0b1a5087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_bot_chats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('bot_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('lesson_id', 'student_id', name='uq_lesson_student_botchat')
    )
    op.create_table('lesson_members',
    sa.Column('lesson_member_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_member_id'),
    sa.UniqueConstraint('lesson_id', 'user_id', name='uq_lesson_member')
    )
    op.create_table('lesson_quizzes',
    sa.Column('quiz_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('allows_multiple_answers', sa.Boolean(), nullable=True),
    sa.Column('show_correct_after_answer', sa.Boolean(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=True),
    sa.Column('shuffle_options', sa.Boolean(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('pass_score', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('quiz_attempts',
    sa.Column('attempt_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('correct_answers_count', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_abandoned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['lesson_quizzes.quiz_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('quiz_questions',
    sa.Column('question_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('correct_explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['lesson_quizzes.quiz_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('question_options',
    sa.Column('option_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_table('quiz_answers',
    sa.Column('answer_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.attempt_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.option_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('lesson_materials',
    sa.Column('material_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attachment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['message_attachments.attachment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.drop_table('bot_sessions')
    op.add_column('lessons', sa.Column('subject', sa.String(length=128), nullable=True))
    op.add_column('lessons', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('lessons', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('lessons', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lessons', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lessons', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_lessons_join_link_hash'), table_name='lessons')
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.drop_constraint(op.f('lessons_bot_user_id_fkey'), 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'bot_user_id')
    op.drop_column('lessons', 'join_link_hash')
    op.add_column('messages', sa.Column('quiz_question_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('quiz_attempt_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'quiz_attempts', ['quiz_attempt_id'], ['attempt_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'quiz_questions', ['quiz_question_id'], ['question_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'quiz_attempt_id')
    op.drop_column('messages', 'quiz_question_id')
    op.add_column('lessons', sa.Column('join_link_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('bot_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('lessons_bot_user_id_fkey'), 'lessons', 'users', ['bot_user_id'], ['user_id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.create_index(op.f('ix_lessons_join_link_hash'), 'lessons', ['join_link_hash'], unique=True)
    op.drop_column('lessons', 'deleted_at')
    op.drop_column('lessons', 'end_date')
    op.drop_column('lessons', 'start_date')
    op.drop_column('lessons', 'is_public')
    op.drop_column('lessons', 'is_active')
    op.drop_column('lessons', 'subject')
    op.create_table('bot_sessions',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('progress_state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_interacted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], name=op.f('bot_sessions_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], name=op.f('bot_sessions_student_id_fkey'), ondelete='CASCADE'),
    sa.UniqueConstraint('student_id', 'lesson_id', name=op.f('uq_student_lesson_session'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('lesson_materials')
    op.drop_table('quiz_answers')
    op.drop_table('question_options')
    op.drop_table('quiz_questions')
    op.drop_table('quiz_attempts')
    op.drop_table('lesson_quizzes')
    op.drop_table('lesson_members')
    op.drop_table('lesson_bot_chats')
    # ### end Alembic commands ###
