"""fix table of user

Revision ID: 6de28087a9a3
Revises: d3b4aeb3556c
Create Date: 2026-04-28 12:30:58.206643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de28087a9a3'
down_revision: Union[str, Sequence[str], None] = 'd3b4aeb3556c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_sessions', sa.Column('user_session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.drop_column('bot_sessions', 'session_id')
    op.add_column('users', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'reset_password_expires_at')
    op.drop_column('users', 'reset_password_token')
    op.add_column('bot_sessions', sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_column('bot_sessions', 'user_session_id')
    # ### end Alembic commands ###
