"""table of chat

Revision ID: c4ff95307cf7
Revises: 6de28087a9a3
Create Date: 2026-04-29 11:31:55.302195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4ff95307cf7'
down_revision: Union[str, Sequence[str], None] = '6de28087a9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_folders',
    sa.Column('folder_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_index('ix_chat_folders_user_id', 'chat_folders', ['user_id'], unique=False)
    op.create_table('chat_folder_items',
    sa.Column('folder_item_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['chat_folders.folder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_item_id'),
    sa.UniqueConstraint('folder_id', 'chat_id', name='uq_folder_chat')
    )
    op.create_index('ix_chat_folder_items_folder_id', 'chat_folder_items', ['folder_id'], unique=False)
    op.create_table('chat_invite_links',
    sa.Column('invite_link_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('member_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('creates_join_request', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('invite_link_id')
    )
    op.create_index('ix_chat_invite_links_chat_id', 'chat_invite_links', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_invite_links_token'), 'chat_invite_links', ['token'], unique=True)
    op.create_table('chat_join_requests',
    sa.Column('join_request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invite_link_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invite_link_id'], ['chat_invite_links.invite_link_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('join_request_id'),
    sa.UniqueConstraint('chat_id', 'user_id', 'status', name='uq_pending_join_request')
    )
    op.create_index('ix_chat_join_requests_chat_status', 'chat_join_requests', ['chat_id', 'status'], unique=False)
    op.create_table('chat_member_permissions',
    sa.Column('permission_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_member_id', sa.UUID(), nullable=False),
    sa.Column('can_send_messages', sa.Boolean(), nullable=False),
    sa.Column('can_send_media', sa.Boolean(), nullable=False),
    sa.Column('can_send_polls', sa.Boolean(), nullable=False),
    sa.Column('can_add_web_page_previews', sa.Boolean(), nullable=False),
    sa.Column('can_invite_users', sa.Boolean(), nullable=False),
    sa.Column('can_pin_messages', sa.Boolean(), nullable=False),
    sa.Column('can_delete_messages', sa.Boolean(), nullable=False),
    sa.Column('can_ban_users', sa.Boolean(), nullable=False),
    sa.Column('can_promote_members', sa.Boolean(), nullable=False),
    sa.Column('can_change_info', sa.Boolean(), nullable=False),
    sa.Column('can_manage_video_chats', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_member_id'], ['chat_members.chat_member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('chat_member_id')
    )
    op.create_table('chat_user_states',
    sa.Column('state_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_member_id', sa.UUID(), nullable=True),
    sa.Column('last_read_message_id', sa.UUID(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_marked_unread', sa.Boolean(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=True),
    sa.Column('cleared_until_message_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_member_id'], ['chat_members.chat_member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cleared_until_message_id'], ['messages.message_id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.message_id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_chat_user_state')
    )
    op.create_index('ix_chat_user_states_chat_user', 'chat_user_states', ['chat_id', 'user_id'], unique=False)
    op.create_index('ix_chat_user_states_user_updated', 'chat_user_states', ['user_id', 'is_archived', 'is_pinned'], unique=False)
    op.create_table('message_attachments',
    sa.Column('attachment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('uploader_id', sa.UUID(), nullable=True),
    sa.Column('attachment_type', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index('ix_message_attachments_message_id', 'message_attachments', ['message_id'], unique=False)
    op.create_index('ix_message_attachments_uploader_id', 'message_attachments', ['uploader_id'], unique=False)
    op.create_table('message_deletions',
    sa.Column('deletion_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deletion_id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_deletion_user')
    )
    op.create_index('ix_message_deletions_chat_user', 'message_deletions', ['chat_id', 'user_id'], unique=False)
    op.create_table('message_reactions',
    sa.Column('reaction_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reaction_id'),
    sa.UniqueConstraint('message_id', 'user_id', 'reaction', name='uq_message_user_reaction')
    )
    op.create_index('ix_message_reactions_chat_id', 'message_reactions', ['chat_id'], unique=False)
    op.create_index('ix_message_reactions_message_id', 'message_reactions', ['message_id'], unique=False)
    op.create_table('message_reads',
    sa.Column('read_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('read_id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_read_user')
    )
    op.create_index('ix_message_reads_chat_user', 'message_reads', ['chat_id', 'user_id'], unique=False)
    op.create_index('ix_message_reads_message_id', 'message_reads', ['message_id'], unique=False)
    op.create_table('pinned_messages',
    sa.Column('pinned_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('pinned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pinned_id'),
    sa.UniqueConstraint('chat_id', 'message_id', name='uq_pinned_message')
    )
    op.create_index('ix_pinned_messages_chat_id', 'pinned_messages', ['chat_id'], unique=False)
    op.add_column('chat_members', sa.Column('custom_title', sa.String(length=64), nullable=True))
    op.add_column('chat_members', sa.Column('invited_by_user_id', sa.UUID(), nullable=True))
    op.add_column('chat_members', sa.Column('left_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chat_members', sa.Column('banned_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chat_members', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_chat_member_user_id'), table_name='chat_members')
    op.create_index('ix_chat_members_chat_id_role', 'chat_members', ['chat_id', 'role'], unique=False)
    op.create_index('ix_chat_members_user_id', 'chat_members', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_members', 'users', ['invited_by_user_id'], ['user_id'], ondelete='SET NULL')
    op.add_column('chats', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('chats', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('chats', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('chats', sa.Column('username', sa.String(length=64), nullable=True))
    op.add_column('chats', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('chats', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('chats', sa.Column('is_scam', sa.Boolean(), nullable=False))
    op.add_column('chats', sa.Column('is_fake', sa.Boolean(), nullable=False))
    op.add_column('chats', sa.Column('slow_mode_seconds', sa.Integer(), nullable=False))
    op.add_column('chats', sa.Column('message_auto_delete_seconds', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('last_message_id', sa.UUID(), nullable=True))
    op.add_column('chats', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chats_chat_type'), 'chats', ['chat_type'], unique=False)
    op.create_index('ix_chats_owner_id', 'chats', ['owner_id'], unique=False)
    op.create_index('ix_chats_type_updated_at', 'chats', ['chat_type', 'updated_at'], unique=False)
    op.create_index(op.f('ix_chats_username'), 'chats', ['username'], unique=True)
    op.create_foreign_key(None, 'chats', 'messages', ['last_message_id'], ['message_id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'chats', 'users', ['owner_id'], ['user_id'], ondelete='SET NULL')
    op.add_column('messages', sa.Column('client_message_id', sa.String(length=128), nullable=True))
    op.add_column('messages', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('reply_to_message_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('forward_from_chat_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('forward_from_message_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('forward_from_user_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('via_bot_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('views_count', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('forwards_count', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('replies_count', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('is_silent', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('edit_count', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_messages_chat_id_created_at'), table_name='messages')
    op.create_index('ix_messages_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('ix_messages_chat_id_id', 'messages', ['chat_id', 'message_id'], unique=False)
    op.create_index('ix_messages_client_message', 'messages', ['chat_id', 'sender_id', 'client_message_id'], unique=False)
    op.create_index('ix_messages_reply_to', 'messages', ['reply_to_message_id'], unique=False)
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_unique_constraint('uq_message_client_id', 'messages', ['chat_id', 'sender_id', 'client_message_id'])
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_message_id'], ['message_id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'messages', 'messages', ['forward_from_message_id'], ['message_id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'messages', 'users', ['forward_from_user_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'users', ['via_bot_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'chats', ['forward_from_chat_id'], ['chat_id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint('uq_message_client_id', 'messages', type_='unique')
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_index('ix_messages_reply_to', table_name='messages')
    op.drop_index('ix_messages_client_message', table_name='messages')
    op.drop_index('ix_messages_chat_id_id', table_name='messages')
    op.drop_index('ix_messages_chat_created', table_name='messages')
    op.create_index(op.f('ix_messages_chat_id_created_at'), 'messages', ['chat_id', 'created_at'], unique=False)
    op.drop_column('messages', 'scheduled_at')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'edit_count')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'is_silent')
    op.drop_column('messages', 'is_pinned')
    op.drop_column('messages', 'replies_count')
    op.drop_column('messages', 'forwards_count')
    op.drop_column('messages', 'views_count')
    op.drop_column('messages', 'via_bot_id')
    op.drop_column('messages', 'forward_from_user_id')
    op.drop_column('messages', 'forward_from_message_id')
    op.drop_column('messages', 'forward_from_chat_id')
    op.drop_column('messages', 'reply_to_message_id')
    op.drop_column('messages', 'metadata_json')
    op.drop_column('messages', 'client_message_id')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_username'), table_name='chats')
    op.drop_index('ix_chats_type_updated_at', table_name='chats')
    op.drop_index('ix_chats_owner_id', table_name='chats')
    op.drop_index(op.f('ix_chats_chat_type'), table_name='chats')
    op.drop_column('chats', 'deleted_at')
    op.drop_column('chats', 'last_message_id')
    op.drop_column('chats', 'message_auto_delete_seconds')
    op.drop_column('chats', 'slow_mode_seconds')
    op.drop_column('chats', 'is_fake')
    op.drop_column('chats', 'is_scam')
    op.drop_column('chats', 'is_verified')
    op.drop_column('chats', 'is_public')
    op.drop_column('chats', 'username')
    op.drop_column('chats', 'owner_id')
    op.drop_column('chats', 'avatar_url')
    op.drop_column('chats', 'description')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_index('ix_chat_members_user_id', table_name='chat_members')
    op.drop_index('ix_chat_members_chat_id_role', table_name='chat_members')
    op.create_index(op.f('ix_chat_member_user_id'), 'chat_members', ['user_id'], unique=False)
    op.drop_column('chat_members', 'is_deleted')
    op.drop_column('chat_members', 'banned_until')
    op.drop_column('chat_members', 'left_at')
    op.drop_column('chat_members', 'invited_by_user_id')
    op.drop_column('chat_members', 'custom_title')
    op.drop_index('ix_pinned_messages_chat_id', table_name='pinned_messages')
    op.drop_table('pinned_messages')
    op.drop_index('ix_message_reads_message_id', table_name='message_reads')
    op.drop_index('ix_message_reads_chat_user', table_name='message_reads')
    op.drop_table('message_reads')
    op.drop_index('ix_message_reactions_message_id', table_name='message_reactions')
    op.drop_index('ix_message_reactions_chat_id', table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index('ix_message_deletions_chat_user', table_name='message_deletions')
    op.drop_table('message_deletions')
    op.drop_index('ix_message_attachments_uploader_id', table_name='message_attachments')
    op.drop_index('ix_message_attachments_message_id', table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index('ix_chat_user_states_user_updated', table_name='chat_user_states')
    op.drop_index('ix_chat_user_states_chat_user', table_name='chat_user_states')
    op.drop_table('chat_user_states')
    op.drop_table('chat_member_permissions')
    op.drop_index('ix_chat_join_requests_chat_status', table_name='chat_join_requests')
    op.drop_table('chat_join_requests')
    op.drop_index(op.f('ix_chat_invite_links_token'), table_name='chat_invite_links')
    op.drop_index('ix_chat_invite_links_chat_id', table_name='chat_invite_links')
    op.drop_table('chat_invite_links')
    op.drop_index('ix_chat_folder_items_folder_id', table_name='chat_folder_items')
    op.drop_table('chat_folder_items')
    op.drop_index('ix_chat_folders_user_id', table_name='chat_folders')
    op.drop_table('chat_folders')
    # ### end Alembic commands ###
