"""
Research report.

Contains every metric generated by the framework.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from ..assessment.result import ResearchMetrics

from ..reports.models import (
    Report,
    GoalSummary,
)


@dataclass(slots=True)
class ResearchReport(Report):

    coverage: float = 0.0

    mastery: float = 0.0

    confidence: float = 0.0

    duration_seconds: float = 0.0

    goals: list[GoalSummary] = field(
        default_factory=list
    )

    metrics: ResearchMetrics | None = None

    timeline: list = field(
        default_factory=list
    )